ARG BASEIMG
ARG IMG_VERSION
FROM $BASEIMG:$IMG_VERSION

ENV REACT_APP_ENV=Production
WORKDIR /app

COPY build/ /app/build
COPY .env /app/.env
COPY .ci/nginx.conf /etc/nginx/nginx.conf
COPY .ci/react_init.sh /app/react_init.sh

EXPOSE 80
RUN chmod +x /app/react_init.sh
ENTRYPOINT [ "/app/react_init.sh" ]
CMD ["nginx"]