apiVersion: v1
kind: Service
metadata:
  name: ${projectname}
  labels:
    app: ${projectname}
spec:
  selector:
    app: ${projectname}

  ports:
    - port: 80
      targetPort: 80
  type: NodePort