FROM pisharpeddemo.azurecr.io/baseimages/ubuntu:jammy-dotnet-sdk-6.0.414

ARG TINI_VERSION=0.19.0
ARG TINI_URL=https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}-amd64.deb

RUN apt-get update \
# Add tini
    && curl -sSL ${TINI_URL} -o /tmp/tini.deb && apt-get install -y --no-install-recommends /tmp/tini.deb \
    && ln -s /usr/bin/tini /usr/local/bin/tini && ln -s /usr/bin/tini-static /usr/local/bin/tini-static; \
#Cleanup
    rm /tmp/tini.deb && rm -rf /var/lib/apt/lists/*