ARG BASEIMG
ARG IMG_VERSION
ARG RUNIMG
ARG RUNVER

FROM $BASEIMG:$IMG_VERSION as publish
ARG DEBUG_MODE

ARG PUBLISH_PROJ
RUN dotnet publish --configuration Release --no-build --no-restore -o /app --runtime linux-x64
    
FROM $RUNIMG:$RUNVER as runtime
ARG ENTRYPOINT

EXPOSE 80 8080 8081
ENV RUNTIME=$ENTRYPOINT
WORKDIR /app
COPY --from=publish /app .
ADD ./ci/docker_entrypoint.sh /app/docker_entrypoint.sh
RUN chmod +x /app/docker_entrypoint.sh
ENTRYPOINT [ "tini", "--", "/app/docker_entrypoint.sh" ]