ARG BASEIMG
ARG IMG_VERSION
ARG RUNIMG
ARG RUNVER

FROM $BASEIMG:$IMG_VERSION as publish

ARG PUBLISH_PROJ
RUN dotnet publish ${PUBLISH_PROJ} --no-build --no-restore -o /app
    
# FROM $RUNIMG:$RUNVER as runtime
ARG ENTRYPOINT

ENV ASPNETCORE_URLS="http://+:8080" \
    RUNTIME=$ENTRYPOINT
EXPOSE 8080

WORKDIR /app
COPY --from=publish /app .
COPY ./.ci/docker_entrypoint.sh /app/docker_entrypoint.sh
RUN chmod +x /app/docker_entrypoint.sh && chmod -R 755 /app

ENTRYPOINT ["tini", "--", "/app/docker_entrypoint.sh"]